//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestExam.Model
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    public partial class Order
    {
        public Order()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int OrderID { get; set; }
        public string OrderStatus { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime OrderDeliveryDate { get; set; }
        public int OrderPickupPoint { get; set; }
        public int UserID { get; set; }
        public int OrderPickUpCode { get; set; }
        public string OrderCode
        {
            get
            {
                return $"Код для получения: {OrderPickUpCode}";
            }
        }
    
        public virtual PickUpPoint PickUpPoint { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public string OrderProducts
        {
            get
            {
                StringBuilder allProducts = new StringBuilder();
                foreach (OrderProduct pr in this.OrderProduct)
                {
                    allProducts.Append($"{pr.Product.ProductName} {pr.CountProducts} шт.\n");
                }
                return allProducts.ToString();
            }
        }
    }
}
